apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: calendar
  labels:
    app.kubernetes.io/name: calendar
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: calendar
  template:
    metadata:
      labels:
        app.kubernetes.io/name: calendar
    spec:
      containers:
      - name: app
        image: ghcr.io/twin-te/calendar-service:master
        env:
        - name: COOKIE_NAME
          value: twinte_session
        - name: API_GATEWAY_BASE_URL
          value: http://api-gateway:3000
        ports:
        - name: http
          containerPort: 5000
        readinessProbe:
          httpGet:
            port: 5000
            path: /healthz
