apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: calendar
  labels:
    app.kubernetes.io/name: calendar
spec:
  selector:
    app.kubernetes.io/name: calendar
  ports:
  - name: http
    port: 5000
